import assemblyai as aai
import os

def transcribe_audio(audio_file_path: str, api_key: str) -> str:
    """
    Transcribes an audio file using the AssemblyAI API.

    Args:
        audio_file_path (str): The path to the audio file to be transcribed.
        api_key (str): Your AssemblyAI API key.

    Returns:
        str: The transcribed text, or None if an error occurred.
    """
    try:
        aai.settings.api_key = api_key
        transcriber = aai.Transcriber()
        transcript = transcriber.transcribe(audio_file_path)

        if transcript.status == aai.TranscriptStatus.error:
            print(f"Error during transcription: {transcript.error}")
            return None
        else:
            return transcript.text

    except Exception as e:
        print(f"An error occurred: {e}")
        return None

if __name__ == "__main__":
    # This is an example of how to use the transcribe_audio function.
    # It is recommended to manage your API keys securely, for example, by using environment variables.
    
    # To run this example, set the ASSEMBLYAI_API_KEY environment variable:
    # export ASSEMBLYAI_API_KEY='your_assemblyai_api_key'
    
    assemblyai_api_key = os.environ.get("ASSEMBLYAI_API_KEY")
    
    if not assemblyai_api_key:
        print("ERROR: The ASSEMBLYAI_API_KEY environment variable is not set.")
        print("Please set it to your AssemblyAI API key.")
    else:
        # You will need a sample audio file to test this.
        # For example, you can use the 'audio.mp3' generated by tts.py.
        # Note: Ensure the file format is supported by AssemblyAI.
        
        # Create a dummy audio file for testing if it doesn't exist
        sample_audio_file = "sample_audio.wav"
        if not os.path.exists(sample_audio_file):
            print(f"Creating a dummy audio file: {sample_audio_file}")
            # This is a simple way to create a silent wav file for testing purposes.
            # In a real scenario, you would use an actual audio file.
            import wave
            with wave.open(sample_audio_file, 'wb') as wf:
                wf.setnchannels(1)
                wf.setsampwidth(2)
                wf.setframerate(44100)
                wf.writeframes(b'\x00\x00' * 44100) # 1 second of silence

        print(f"Transcribing audio file: {sample_audio_file}")
        transcribed_text = transcribe_audio(sample_audio_file, assemblyai_api_key)
        
        if transcribed_text:
            print(f"Successfully transcribed audio.")
            print(f"Transcription: {transcribed_text}")
        else:
            print("Failed to transcribe audio.")
